{-# LANGUAGE OverloadedStrings #-}

import System.Environment
import Web.Scotty
import qualified Data.Text.Lazy as TL

main :: IO ()
main = do
    port:_ <- getArgs
    scotty (read port) $ do
        get "/echo/hello-world" $ text "Hello World"
        get "/echo/plain/:param/:int" $ do
            p <- param "param"
            i <- param "int"
            text . TL.fromChunks $ replicate i p

        get "/deep/foo/bar/baz/0" $ text "deep"
        get "/deep/foo/bar/baz/1" $ text "deep"
        get "/deep/foo/bar/baz/2" $ text "deep"
        get "/deep/foo/bar/baz/3" $ text "deep"
        get "/deep/foo/bar/baz/4" $ text "deep"
        get "/deep/foo/bar/baz/5" $ text "deep"
        get "/deep/foo/bar/baz/6" $ text "deep"
        get "/deep/foo/bar/baz/7" $ text "deep"
        get "/deep/foo/bar/baz/8" $ text "deep"
        get "/deep/foo/bar/baz/9" $ text "deep"
        get "/deep/foo/bar/baz/10" $ text "deep"
        get "/deep/foo/bar/baz/11" $ text "deep"
        get "/deep/foo/bar/baz/12" $ text "deep"
        get "/deep/foo/bar/baz/13" $ text "deep"
        get "/deep/foo/bar/baz/14" $ text "deep"
        get "/deep/foo/bar/baz/15" $ text "deep"
        get "/deep/foo/bar/baz/16" $ text "deep"
        get "/deep/foo/bar/baz/17" $ text "deep"
        get "/deep/foo/bar/baz/18" $ text "deep"
        get "/deep/foo/bar/baz/19" $ text "deep"
        get "/deep/foo/bar/baz/20" $ text "deep"
        get "/deep/foo/bar/baz/21" $ text "deep"
        get "/deep/foo/bar/baz/22" $ text "deep"
        get "/deep/foo/bar/baz/23" $ text "deep"
        get "/deep/foo/bar/baz/24" $ text "deep"
        get "/deep/foo/bar/baz/25" $ text "deep"
        get "/deep/foo/bar/baz/26" $ text "deep"
        get "/deep/foo/bar/baz/27" $ text "deep"
        get "/deep/foo/bar/baz/28" $ text "deep"
        get "/deep/foo/bar/baz/29" $ text "deep"
        get "/deep/foo/bar/baz/30" $ text "deep"
        get "/deep/foo/bar/baz/31" $ text "deep"
        get "/deep/foo/bar/baz/32" $ text "deep"
        get "/deep/foo/bar/baz/33" $ text "deep"
        get "/deep/foo/bar/baz/34" $ text "deep"
        get "/deep/foo/bar/baz/35" $ text "deep"
        get "/deep/foo/bar/baz/36" $ text "deep"
        get "/deep/foo/bar/baz/37" $ text "deep"
        get "/deep/foo/bar/baz/38" $ text "deep"
        get "/deep/foo/bar/baz/39" $ text "deep"
        get "/deep/foo/bar/baz/40" $ text "deep"
        get "/deep/foo/bar/baz/41" $ text "deep"
        get "/deep/foo/bar/baz/42" $ text "deep"
        get "/deep/foo/bar/baz/43" $ text "deep"
        get "/deep/foo/bar/baz/44" $ text "deep"
        get "/deep/foo/bar/baz/45" $ text "deep"
        get "/deep/foo/bar/baz/46" $ text "deep"
        get "/deep/foo/bar/baz/47" $ text "deep"
        get "/deep/foo/bar/baz/48" $ text "deep"
        get "/deep/foo/bar/baz/49" $ text "deep"
        get "/deep/foo/bar/baz/50" $ text "deep"
        get "/deep/foo/bar/baz/51" $ text "deep"
        get "/deep/foo/bar/baz/52" $ text "deep"
        get "/deep/foo/bar/baz/53" $ text "deep"
        get "/deep/foo/bar/baz/54" $ text "deep"
        get "/deep/foo/bar/baz/55" $ text "deep"
        get "/deep/foo/bar/baz/56" $ text "deep"
        get "/deep/foo/bar/baz/57" $ text "deep"
        get "/deep/foo/bar/baz/58" $ text "deep"
        get "/deep/foo/bar/baz/59" $ text "deep"
        get "/deep/foo/bar/baz/60" $ text "deep"
        get "/deep/foo/bar/baz/61" $ text "deep"
        get "/deep/foo/bar/baz/62" $ text "deep"
        get "/deep/foo/bar/baz/63" $ text "deep"
        get "/deep/foo/bar/baz/64" $ text "deep"
        get "/deep/foo/bar/baz/65" $ text "deep"
        get "/deep/foo/bar/baz/66" $ text "deep"
        get "/deep/foo/bar/baz/67" $ text "deep"
        get "/deep/foo/bar/baz/68" $ text "deep"
        get "/deep/foo/bar/baz/69" $ text "deep"
        get "/deep/foo/bar/baz/70" $ text "deep"
        get "/deep/foo/bar/baz/71" $ text "deep"
        get "/deep/foo/bar/baz/72" $ text "deep"
        get "/deep/foo/bar/baz/73" $ text "deep"
        get "/deep/foo/bar/baz/74" $ text "deep"
        get "/deep/foo/bar/baz/75" $ text "deep"
        get "/deep/foo/bar/baz/76" $ text "deep"
        get "/deep/foo/bar/baz/77" $ text "deep"
        get "/deep/foo/bar/baz/78" $ text "deep"
        get "/deep/foo/bar/baz/79" $ text "deep"
        get "/deep/foo/bar/baz/80" $ text "deep"
        get "/deep/foo/bar/baz/81" $ text "deep"
        get "/deep/foo/bar/baz/82" $ text "deep"
        get "/deep/foo/bar/baz/83" $ text "deep"
        get "/deep/foo/bar/baz/84" $ text "deep"
        get "/deep/foo/bar/baz/85" $ text "deep"
        get "/deep/foo/bar/baz/86" $ text "deep"
        get "/deep/foo/bar/baz/87" $ text "deep"
        get "/deep/foo/bar/baz/88" $ text "deep"
        get "/deep/foo/bar/baz/89" $ text "deep"
        get "/deep/foo/bar/baz/90" $ text "deep"
        get "/deep/foo/bar/baz/91" $ text "deep"
        get "/deep/foo/bar/baz/92" $ text "deep"
        get "/deep/foo/bar/baz/93" $ text "deep"
        get "/deep/foo/bar/baz/94" $ text "deep"
        get "/deep/foo/bar/baz/95" $ text "deep"
        get "/deep/foo/bar/baz/96" $ text "deep"
        get "/deep/foo/bar/baz/97" $ text "deep"
        get "/deep/foo/bar/baz/98" $ text "deep"
        get "/deep/foo/bar/baz/99" $ text "deep"
        get "/deep/foo/bar/baz/100" $ text "deep"

        get "/after" $ text "after"
